
import java.rmi.Naming;
import java.util.Properties;
import javax.mail.Message.RecipientType;
import javax.mail.MessagingException;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.AddressException;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pragya
 */
public class pmailupdate extends javax.swing.JFrame {
    static String id,ip;
    String email;
    public pmailupdate(String id,String ip) {
        initComponents();
        this.setSize(275,737);
        this.setLocation(1088, 0);
        this.setTitle("Update Password");
        jLabel6.setVisible(false);
        this.ip=ip;
        getuniquecode();
        try
            {
                MiddleApp app=(MiddleApp)Naming.lookup("rmi://"+ip+"/signup");
                email= app.emailfetch(id);
               
                
            }catch(Exception e)
            {
                System.out.println(e);
            }
        System.out.println(email);
        send("Your code is "+code, email);
    }
    String code="";
    void getuniquecode()
    {
        code="";
        String s="0123456789"; 
        int len=s.length();
        for(int j=0;j<4;j++)
        {
            int rand=(int)(len*(Math.random()));
            char ra=s.charAt(rand);
            code+=ra;
        }
    }
    public void send(String content,String to)
    {
        String from = "bishnuvisha@gmail.com";
        String host = "smtp.gmail.com";
        String userid = "bishnuvisha"; 
        String password = "narendramodi@123"; 
        String subject="Update Password::Code";
        try
        {
            Properties props = System.getProperties(); 
            props.put("mail.smtp.starttls.enable", "true"); 
            props.put("mail.smtp.host", host); 
            props.setProperty("mail.transport.protocol", "smtps");
            props.put("mail.smtp.user", userid); 
            props.put("mail.smtp.password", password); 
            props.put("mail.smtp.port", "465"); 
            props.put("mail.smtps.auth", "true"); 
            Session session = Session.getDefaultInstance(props, null); 
            MimeMessage message = new MimeMessage(session); 
            InternetAddress fromAddress = null;
            InternetAddress toAddress = null;
            try {
                fromAddress = new InternetAddress(from);
                toAddress = new InternetAddress(to);
            } catch (AddressException e) {
                e.printStackTrace();
            }
            message.setFrom(fromAddress);
            message.setRecipient(RecipientType.TO, toAddress);
            message.setSubject(subject);
            message.setText(content); 
            Transport transport = session.getTransport("smtps"); 
            transport.connect(host, userid, password); 
            transport.sendMessage(message, message.getAllRecipients()); 
            transport.close(); 
            } catch (MessagingException e) {
            System.out.println(e);
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter the Received code here...");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 140, 230, 17);

        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 153)));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(20, 180, 210, 23);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Submit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(20, 220, 80, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Enter New Password:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 440, 160, 17);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Submit.png"))); // NOI18N
        jButton2.setEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(20, 540, 90, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Update Password");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 330, 220, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maintitle.png"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 20, 260, 80);

        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 250, 210, 20);

        jPasswordField1.setEnabled(false);
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(20, 490, 220, 22);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(0, 282, 280, 420);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/blue.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 280, 752);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(code.equals(jTextField1.getText()))
        {
            jPasswordField1.setEnabled(true);
            jButton2.setEnabled(true);
        }
        else if(code.equals(""))
        {
            jLabel6.setVisible(true);
            jLabel6.setText("Invalid code");
        }
        else
        {
            jLabel6.setVisible(true);
            jLabel6.setText("Re-enter code");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       String pass;
        try
        {
            pass=jPasswordField1.getText();
            MiddleApp app=(MiddleApp)Naming.lookup("rmi://"+ip+"/signup");
            int j=app.mailupdatepass(id,pass);
            if(j==0)
            {
                System.out.println(j);
            }
           else
            {
            System.out.println(j);
            new signup_in(ip).setVisible(true);
            }

        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pmailupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pmailupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pmailupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pmailupdate.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new pmailupdate(id,ip).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
