
import java.awt.AlphaComposite;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.awt.image.ImageFilter;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.rmi.Naming;
import javax.imageio.ImageIO;
import javax.imageio.stream.FileImageInputStream;
import javax.swing.*;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pragya
 */
public class uploadpic extends javax.swing.JFrame {
    
   static String ip,id,name;
    public uploadpic(String ip,String id,String name) {
        
        initComponents();
        this.setSize(275,736);
        this.setLocation(1088, 0);
        this.setTitle("Upload Image");
        jLabel4.setText(name);
        this.ip=ip;
        this.id=id;
        this.name=name;
    }
    public static BufferedImage resizeImage(BufferedImage originalImage, int type){
	BufferedImage resizedImage = new BufferedImage(160, 150, type);
	Graphics2D g = resizedImage.createGraphics();
	g.drawImage(originalImage, 0, 0, 160, 150, null);
	g.dispose();
 
	return resizedImage;
    }
    private static BufferedImage resizeImageWithHint(BufferedImage originalImage, int type){
        BufferedImage resizedImage = new BufferedImage(160, 150, type);
	Graphics2D g = resizedImage.createGraphics();
	g.drawImage(originalImage, 0, 0, 160, 150, null);
	g.dispose();	
	g.setComposite(AlphaComposite.Src);
 
	g.setRenderingHint(RenderingHints.KEY_INTERPOLATION,
	RenderingHints.VALUE_INTERPOLATION_BILINEAR);
	g.setRenderingHint(RenderingHints.KEY_RENDERING,
	RenderingHints.VALUE_RENDER_QUALITY);
	g.setRenderingHint(RenderingHints.KEY_ANTIALIASING,
	RenderingHints.VALUE_ANTIALIAS_ON);
 
        return resizedImage;
    }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upload.png"))); // NOI18N
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(40, 430, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defaultpic.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 255), 5));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 190, 160, 150);

        jButton2.setText("skip");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(160, 430, 55, 25);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 110, 220, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 0));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/maintitle.png"))); // NOI18N
        jLabel3.setText("Upload Pic");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 40, 260, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\varjava\\1\\src\\blue.png")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 270, 790);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    String file,path,type;
    int w,l,pos;
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       JFileChooser chooser = new JFileChooser();
       int returnVal = chooser.showOpenDialog(null);
       if(returnVal == JFileChooser.APPROVE_OPTION)
       {
        file=chooser.getSelectedFile().getPath();   
       try{
 
		BufferedImage originalImage = ImageIO.read(new File(file));
		int type = originalImage.getType() == 0? BufferedImage.TYPE_INT_ARGB : originalImage.getType();
 
		BufferedImage resizeImageJpg = resizeImage(originalImage, type);
		ImageIO.write(resizeImageJpg, "jpg", new File(file)); 
 
		BufferedImage resizeImagePng = resizeImage(originalImage, type);
		ImageIO.write(resizeImagePng, "png", new File(file)); 
 
		BufferedImage resizeImageHintJpg = resizeImageWithHint(originalImage, type);
		ImageIO.write(resizeImageHintJpg, "jpg", new File(file)); 
 
		BufferedImage resizeImageHintPng = resizeImageWithHint(originalImage, type);
		ImageIO.write(resizeImageHintPng, "png", new File(file)); 
 
	}catch(IOException e){
		System.out.println(e.getMessage());
	}
       }
    
 
   
        ImageIcon icon=new ImageIcon(file);
        jLabel1.setIcon(icon);
        try
        {   
            BufferedInputStream bin=new BufferedInputStream(new FileInputStream(file));
            int totalBytes=bin.available();
            byte b[]=new byte[totalBytes];
            int bytes=0,bytesRead=0;
            while(bytesRead<totalBytes)
            {
                bytes=bin.read(b, bytesRead, totalBytes);
                bytesRead+=bytes;
            }
            bin.close();
            MiddleApp app=(MiddleApp)Naming.lookup("rmi://"+ip+"/signup");
            String n=app.pic(id,file,b);
            if(n.equals("upload"))
            {
                JOptionPane.showMessageDialog(this," pic uploaded ");
                this.dispose();
                new signup_in(ip).setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"not registered....try again");
            }
           
        }
        catch(Exception e)
        {
            System.out.println(e);
        }

     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      String pic=System.getProperty("user.dir")+File.separator+"defaultimage"+File.separator+"defaultpic.png";
        try
        {   
            BufferedInputStream bin=new BufferedInputStream(new FileInputStream(pic));
            int totalBytes=bin.available();
            byte b[]=new byte[totalBytes];
            int bytes=0,bytesRead=0;
            while(bytesRead<totalBytes)
            {
                bytes=bin.read(b, bytesRead, totalBytes);
                bytesRead+=bytes;
            }
            bin.close();
            MiddleApp app=(MiddleApp)Naming.lookup("rmi://"+ip+"/signup");
            String n=app.pic(id,pic,b);
            if(n.equals("upload"))
            {
                //JOptionPane.showMessageDialog(this," pic uploaded ");
                this.dispose();
                new signup_in(ip).setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"not registered....try again");
            }
           
        }
        catch(Exception e)
        {
            System.out.println(e);
        }  
 

    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(uploadpic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(uploadpic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(uploadpic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(uploadpic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new uploadpic("localhost",id,name).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
